#!/bin/sh
TIMELY_BUILD=$2
MODULE_LIST=$3


build_project()
{
        project_name=$2
        build_path=$1/$project_name
	echo "#################### [Start to build $project_name !!!] #################### "
	echo "######################################################################################"
	echo ""

	cd $build_path
	old_bin=`find bin/ -executable -type f`
	if [ -f $old_bin ]; then
		rm -rf $old_bin
	fi

	if [ 'X${TIMELY_BUILD}' == '0' ]; then
		make clean
	fi

	# 每天11, 23点执行 clean操作
	current_hour=`date +%k`
	if [ "23" == $current_hour ] ; then
		make clean
	fi
	
	make all -j4
	cd - 

	echo ""
	echo "#################### [Build $project_name Finished!!!] #################### " 
	echo "######################################################################################"
	echo ""
}

############################################################################
############################################################################
source_parameter()
{
	DEPLOY_CONFIG_FILE=$1
	if [ "${DEPLOY_CONFIG_FILE%/*}" != "$DEPLOY_CONFIG_FILE" ]; then
                source ${DEPLOY_CONFIG_FILE%/*}/./${DEPLOY_CONFIG_FILE##*/}
        else
                source ./$DEPLOY_CONFIG_FILE
        fi
}

build_all()
{
	echo "build_all entry ... "
	source_parameter $1
	for module_name in ${MODULE_LIST[@]}
	do
		# traversal module name
		eval project_list=\${$module_name[@]}
		echo $module_name

		# get all project from the module
		for project_name in ${project_list[@]}
		do
			temp_path=${project_name%/*}
			temp_name=${project_name##*/}
			#echo $temp_path $temp_name

			build_project  $temp_path $temp_name
		done
	done

	echo "build_all leave ... "
}


#######################################[main]#######################################
main()
{
	mkdir -p build
	echo "BUILD_NUMBER=$BUILD_NUMBER" > build/build_number
	
	build_all $1
#	BUILD_PROJECT=$1
#	temp_path=${BUILD_PROJECT%/*}
#	temp_name=${BUILD_PROJECT##*/}
#	echo $temp_path $temp_name
#	build_project $temp_path $temp_name
}

if [ $# -lt 2 ]; then
	echo "MAKE ****** [ERROR] ******"
	echo "[USAGE] $0 db.cfg 0|1"
	exit
fi

#######################################[main]#######################################
main $1 $2
