# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QDP_main_frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import QDP_basic_info_pb2
import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='QDP_main_frame.proto',
  package='QDP_main_frame',
  serialized_pb=_b('\n\x14QDP_main_frame.proto\x12\x0eQDP_main_frame\x1a\x14QDP_basic_info.proto\x1a\x0c\x63ommon.proto\"\xfd\x01\n\x15user_verification_ask\x12-\n\x04info\x18\x01 \x01(\x0b\x32\x1f.QDP_basic_info.user_basic_info\x12\x35\n\rplatform_type\x18\x02 \x01(\x0e\x32\x1e.QDP_main_frame.other_platform\x12-\n\nask_header\x18\x03 \x01(\x0b\x32\x19.common.common_ask_header\x12\x38\n\x0fservice_manager\x18\x04 \x01(\x0b\x32\x1f.QDP_basic_info.control_service\x12\x15\n\nquery_type\x18\x05 \x01(\x05:\x01\x30\"\x82\x01\n\x15user_verification_ans\x12\x35\n\rplatform_type\x18\x01 \x01(\x0e\x32\x1e.QDP_main_frame.other_platform\x12\x10\n\x08json_ans\x18\x02 \x01(\x0c\x12 \n\x05\x65rror\x18\x03 \x01(\x0b\x32\x11.common.errorinfo*`\n\x0eother_platform\x12\x14\n\x10unknown_platform\x10\x00\x12\x11\n\rCredit_sesame\x10\x01\x12\x10\n\x0c\x66raud_metrix\x10\x02\x12\x13\n\x0f\x41nRong_Platform\x10\x03')
  ,
  dependencies=[QDP_basic_info_pb2.DESCRIPTOR,common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_OTHER_PLATFORM = _descriptor.EnumDescriptor(
  name='other_platform',
  full_name='QDP_main_frame.other_platform',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='unknown_platform', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Credit_sesame', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fraud_metrix', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AnRong_Platform', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=465,
  serialized_end=561,
)
_sym_db.RegisterEnumDescriptor(_OTHER_PLATFORM)

other_platform = enum_type_wrapper.EnumTypeWrapper(_OTHER_PLATFORM)
unknown_platform = 0
Credit_sesame = 1
fraud_metrix = 2
AnRong_Platform = 3



_USER_VERIFICATION_ASK = _descriptor.Descriptor(
  name='user_verification_ask',
  full_name='QDP_main_frame.user_verification_ask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='QDP_main_frame.user_verification_ask.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform_type', full_name='QDP_main_frame.user_verification_ask.platform_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ask_header', full_name='QDP_main_frame.user_verification_ask.ask_header', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_manager', full_name='QDP_main_frame.user_verification_ask.service_manager', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query_type', full_name='QDP_main_frame.user_verification_ask.query_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=330,
)


_USER_VERIFICATION_ANS = _descriptor.Descriptor(
  name='user_verification_ans',
  full_name='QDP_main_frame.user_verification_ans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform_type', full_name='QDP_main_frame.user_verification_ans.platform_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='json_ans', full_name='QDP_main_frame.user_verification_ans.json_ans', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='QDP_main_frame.user_verification_ans.error', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=463,
)

_USER_VERIFICATION_ASK.fields_by_name['info'].message_type = QDP_basic_info_pb2._USER_BASIC_INFO
_USER_VERIFICATION_ASK.fields_by_name['platform_type'].enum_type = _OTHER_PLATFORM
_USER_VERIFICATION_ASK.fields_by_name['ask_header'].message_type = common_pb2._COMMON_ASK_HEADER
_USER_VERIFICATION_ASK.fields_by_name['service_manager'].message_type = QDP_basic_info_pb2._CONTROL_SERVICE
_USER_VERIFICATION_ANS.fields_by_name['platform_type'].enum_type = _OTHER_PLATFORM
_USER_VERIFICATION_ANS.fields_by_name['error'].message_type = common_pb2._ERRORINFO
DESCRIPTOR.message_types_by_name['user_verification_ask'] = _USER_VERIFICATION_ASK
DESCRIPTOR.message_types_by_name['user_verification_ans'] = _USER_VERIFICATION_ANS
DESCRIPTOR.enum_types_by_name['other_platform'] = _OTHER_PLATFORM

user_verification_ask = _reflection.GeneratedProtocolMessageType('user_verification_ask', (_message.Message,), dict(
  DESCRIPTOR = _USER_VERIFICATION_ASK,
  __module__ = 'QDP_main_frame_pb2'
  # @@protoc_insertion_point(class_scope:QDP_main_frame.user_verification_ask)
  ))
_sym_db.RegisterMessage(user_verification_ask)

user_verification_ans = _reflection.GeneratedProtocolMessageType('user_verification_ans', (_message.Message,), dict(
  DESCRIPTOR = _USER_VERIFICATION_ANS,
  __module__ = 'QDP_main_frame_pb2'
  # @@protoc_insertion_point(class_scope:QDP_main_frame.user_verification_ans)
  ))
_sym_db.RegisterMessage(user_verification_ans)


# @@protoc_insertion_point(module_scope)
