# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UBAS_QDP.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='UBAS_QDP.proto',
  package='BUAS_QDP',
  serialized_pb=_b('\n\x0eUBAS_QDP.proto\x12\x08\x42UAS_QDP\x1a\x0c\x63ommon.proto\"1\n\rLocationPoint\x12\x0f\n\x07lng_lat\x18\x01 \x01(\x0c\x12\x0f\n\x07localID\x18\x02 \x01(\x0c\"F\n\x15Location2Position_ask\x12-\n\x0clng_lat_list\x18\x01 \x03(\x0b\x32\x17.BUAS_QDP.LocationPoint\"G\n\x0cLocationInfo\x12\x15\n\rposition_info\x18\x01 \x01(\x0c\x12\x0f\n\x07localID\x18\x02 \x01(\x0c\x12\x0f\n\x07lng_lat\x18\x03 \x01(\x0c\"h\n\x15Location2Position_ans\x12 \n\x05\x65rror\x18\x01 \x01(\x0b\x32\x11.common.errorinfo\x12-\n\rposition_info\x18\x02 \x03(\x0b\x32\x16.BUAS_QDP.LocationInfo\"\x97\x01\n\x17ZhimaDataFlowReflux_ask\x12<\n\x15user_credentials_type\x18\x01 \x01(\x0e\x32\x1d.BUAS_QDP.UserCredentialsType\x12\x15\n\ridentity_card\x18\x02 \x01(\x0c\x12\x11\n\treal_name\x18\x03 \x01(\x0c\x12\x14\n\x0cmobile_phone\x18\x04 \x01(\x0c\"\xa3\x01\n\x0eLoanRecordInfo\x12\x0f\n\x07orderNo\x18\x01 \x01(\x0c\x12\x11\n\torderType\x18\x02 \x01(\x0c\x12\x0f\n\x07\x62izType\x18\x03 \x01(\x0c\x12\x15\n\rgmtOrderStart\x18\x04 \x01(\x0c\x12\x0e\n\x06gmtDue\x18\x05 \x01(\x0c\x12\x0f\n\x07payFreq\x18\x06 \x01(\x0c\x12\x10\n\x08payMonth\x18\x07 \x01(\x0c\x12\x12\n\ngmtOvdDate\x18\x08 \x01(\x0c\"X\n\x10\x41ssureRecordInfo\x12\x10\n\x08identity\x18\x01 \x01(\x0c\x12\x0f\n\x07orderNo\x18\x02 \x01(\x0c\x12\x11\n\torderType\x18\x03 \x01(\x0c\x12\x0e\n\x06guaAmt\x18\x04 \x01(\x0c\"\x9c\x02\n\x17ZhimaDataFlowReflux_ans\x12<\n\x15user_credentials_type\x18\x01 \x01(\x0e\x32\x1d.BUAS_QDP.UserCredentialsType\x12\x15\n\ridentity_card\x18\x02 \x01(\x0c\x12\x11\n\treal_name\x18\x03 \x01(\x0c\x12\x14\n\x0cmobile_phone\x18\x04 \x01(\x0c\x12+\n\tloan_info\x18\x05 \x03(\x0b\x32\x18.BUAS_QDP.LoanRecordInfo\x12/\n\x0b\x61ssure_info\x18\x06 \x03(\x0b\x32\x1a.BUAS_QDP.AssureRecordInfo\x12\x11\n\tremindCnt\x18\x07 \x01(\x0c\x12\x12\n\namtOverdue\x18\x08 \x01(\x0c*.\n\x13UserCredentialsType\x12\x0b\n\x07Unknown\x10\x00\x12\n\n\x06IDCard\x10\x01')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_USERCREDENTIALSTYPE = _descriptor.EnumDescriptor(
  name='UserCredentialsType',
  full_name='BUAS_QDP.UserCredentialsType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDCard', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1041,
  serialized_end=1087,
)
_sym_db.RegisterEnumDescriptor(_USERCREDENTIALSTYPE)

UserCredentialsType = enum_type_wrapper.EnumTypeWrapper(_USERCREDENTIALSTYPE)
Unknown = 0
IDCard = 1



_LOCATIONPOINT = _descriptor.Descriptor(
  name='LocationPoint',
  full_name='BUAS_QDP.LocationPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lng_lat', full_name='BUAS_QDP.LocationPoint.lng_lat', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localID', full_name='BUAS_QDP.LocationPoint.localID', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=91,
)


_LOCATION2POSITION_ASK = _descriptor.Descriptor(
  name='Location2Position_ask',
  full_name='BUAS_QDP.Location2Position_ask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lng_lat_list', full_name='BUAS_QDP.Location2Position_ask.lng_lat_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=163,
)


_LOCATIONINFO = _descriptor.Descriptor(
  name='LocationInfo',
  full_name='BUAS_QDP.LocationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position_info', full_name='BUAS_QDP.LocationInfo.position_info', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localID', full_name='BUAS_QDP.LocationInfo.localID', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lng_lat', full_name='BUAS_QDP.LocationInfo.lng_lat', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=236,
)


_LOCATION2POSITION_ANS = _descriptor.Descriptor(
  name='Location2Position_ans',
  full_name='BUAS_QDP.Location2Position_ans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='BUAS_QDP.Location2Position_ans.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_info', full_name='BUAS_QDP.Location2Position_ans.position_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=342,
)


_ZHIMADATAFLOWREFLUX_ASK = _descriptor.Descriptor(
  name='ZhimaDataFlowReflux_ask',
  full_name='BUAS_QDP.ZhimaDataFlowReflux_ask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_credentials_type', full_name='BUAS_QDP.ZhimaDataFlowReflux_ask.user_credentials_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity_card', full_name='BUAS_QDP.ZhimaDataFlowReflux_ask.identity_card', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_name', full_name='BUAS_QDP.ZhimaDataFlowReflux_ask.real_name', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobile_phone', full_name='BUAS_QDP.ZhimaDataFlowReflux_ask.mobile_phone', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=496,
)


_LOANRECORDINFO = _descriptor.Descriptor(
  name='LoanRecordInfo',
  full_name='BUAS_QDP.LoanRecordInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderNo', full_name='BUAS_QDP.LoanRecordInfo.orderNo', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderType', full_name='BUAS_QDP.LoanRecordInfo.orderType', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bizType', full_name='BUAS_QDP.LoanRecordInfo.bizType', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gmtOrderStart', full_name='BUAS_QDP.LoanRecordInfo.gmtOrderStart', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gmtDue', full_name='BUAS_QDP.LoanRecordInfo.gmtDue', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payFreq', full_name='BUAS_QDP.LoanRecordInfo.payFreq', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payMonth', full_name='BUAS_QDP.LoanRecordInfo.payMonth', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gmtOvdDate', full_name='BUAS_QDP.LoanRecordInfo.gmtOvdDate', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=662,
)


_ASSURERECORDINFO = _descriptor.Descriptor(
  name='AssureRecordInfo',
  full_name='BUAS_QDP.AssureRecordInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='BUAS_QDP.AssureRecordInfo.identity', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderNo', full_name='BUAS_QDP.AssureRecordInfo.orderNo', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderType', full_name='BUAS_QDP.AssureRecordInfo.orderType', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guaAmt', full_name='BUAS_QDP.AssureRecordInfo.guaAmt', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=752,
)


_ZHIMADATAFLOWREFLUX_ANS = _descriptor.Descriptor(
  name='ZhimaDataFlowReflux_ans',
  full_name='BUAS_QDP.ZhimaDataFlowReflux_ans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_credentials_type', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.user_credentials_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity_card', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.identity_card', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_name', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.real_name', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobile_phone', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.mobile_phone', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loan_info', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.loan_info', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assure_info', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.assure_info', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remindCnt', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.remindCnt', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amtOverdue', full_name='BUAS_QDP.ZhimaDataFlowReflux_ans.amtOverdue', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=1039,
)

_LOCATION2POSITION_ASK.fields_by_name['lng_lat_list'].message_type = _LOCATIONPOINT
_LOCATION2POSITION_ANS.fields_by_name['error'].message_type = common_pb2._ERRORINFO
_LOCATION2POSITION_ANS.fields_by_name['position_info'].message_type = _LOCATIONINFO
_ZHIMADATAFLOWREFLUX_ASK.fields_by_name['user_credentials_type'].enum_type = _USERCREDENTIALSTYPE
_ZHIMADATAFLOWREFLUX_ANS.fields_by_name['user_credentials_type'].enum_type = _USERCREDENTIALSTYPE
_ZHIMADATAFLOWREFLUX_ANS.fields_by_name['loan_info'].message_type = _LOANRECORDINFO
_ZHIMADATAFLOWREFLUX_ANS.fields_by_name['assure_info'].message_type = _ASSURERECORDINFO
DESCRIPTOR.message_types_by_name['LocationPoint'] = _LOCATIONPOINT
DESCRIPTOR.message_types_by_name['Location2Position_ask'] = _LOCATION2POSITION_ASK
DESCRIPTOR.message_types_by_name['LocationInfo'] = _LOCATIONINFO
DESCRIPTOR.message_types_by_name['Location2Position_ans'] = _LOCATION2POSITION_ANS
DESCRIPTOR.message_types_by_name['ZhimaDataFlowReflux_ask'] = _ZHIMADATAFLOWREFLUX_ASK
DESCRIPTOR.message_types_by_name['LoanRecordInfo'] = _LOANRECORDINFO
DESCRIPTOR.message_types_by_name['AssureRecordInfo'] = _ASSURERECORDINFO
DESCRIPTOR.message_types_by_name['ZhimaDataFlowReflux_ans'] = _ZHIMADATAFLOWREFLUX_ANS
DESCRIPTOR.enum_types_by_name['UserCredentialsType'] = _USERCREDENTIALSTYPE

LocationPoint = _reflection.GeneratedProtocolMessageType('LocationPoint', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONPOINT,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.LocationPoint)
  ))
_sym_db.RegisterMessage(LocationPoint)

Location2Position_ask = _reflection.GeneratedProtocolMessageType('Location2Position_ask', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION2POSITION_ASK,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.Location2Position_ask)
  ))
_sym_db.RegisterMessage(Location2Position_ask)

LocationInfo = _reflection.GeneratedProtocolMessageType('LocationInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONINFO,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.LocationInfo)
  ))
_sym_db.RegisterMessage(LocationInfo)

Location2Position_ans = _reflection.GeneratedProtocolMessageType('Location2Position_ans', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION2POSITION_ANS,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.Location2Position_ans)
  ))
_sym_db.RegisterMessage(Location2Position_ans)

ZhimaDataFlowReflux_ask = _reflection.GeneratedProtocolMessageType('ZhimaDataFlowReflux_ask', (_message.Message,), dict(
  DESCRIPTOR = _ZHIMADATAFLOWREFLUX_ASK,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.ZhimaDataFlowReflux_ask)
  ))
_sym_db.RegisterMessage(ZhimaDataFlowReflux_ask)

LoanRecordInfo = _reflection.GeneratedProtocolMessageType('LoanRecordInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOANRECORDINFO,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.LoanRecordInfo)
  ))
_sym_db.RegisterMessage(LoanRecordInfo)

AssureRecordInfo = _reflection.GeneratedProtocolMessageType('AssureRecordInfo', (_message.Message,), dict(
  DESCRIPTOR = _ASSURERECORDINFO,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.AssureRecordInfo)
  ))
_sym_db.RegisterMessage(AssureRecordInfo)

ZhimaDataFlowReflux_ans = _reflection.GeneratedProtocolMessageType('ZhimaDataFlowReflux_ans', (_message.Message,), dict(
  DESCRIPTOR = _ZHIMADATAFLOWREFLUX_ANS,
  __module__ = 'UBAS_QDP_pb2'
  # @@protoc_insertion_point(class_scope:BUAS_QDP.ZhimaDataFlowReflux_ans)
  ))
_sym_db.RegisterMessage(ZhimaDataFlowReflux_ans)


# @@protoc_insertion_point(module_scope)
