# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UPS_login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='UPS_login.proto',
  package='UPS_login',
  serialized_pb=_b('\n\x0fUPS_login.proto\x12\tUPS_login\x1a\x0c\x63ommon.proto\"c\n\nlogin_info\x12\x16\n\x0euser_image_url\x18\x01 \x01(\x0c\x12\x13\n\x0buser_label1\x18\x02 \x01(\x0c\x12\x13\n\x0buser_label2\x18\x03 \x01(\x0c\x12\x13\n\x0buser_label3\x18\x04 \x01(\x0c\"%\n\x0elogin_info_ask\x12\x13\n\x0buser_number\x18\x01 \x01(\x05\"W\n\x0elogin_info_ans\x12#\n\x04info\x18\x01 \x03(\x0b\x32\x15.UPS_login.login_info\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.common.errorinfo')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGIN_INFO = _descriptor.Descriptor(
  name='login_info',
  full_name='UPS_login.login_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_image_url', full_name='UPS_login.login_info.user_image_url', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_label1', full_name='UPS_login.login_info.user_label1', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_label2', full_name='UPS_login.login_info.user_label2', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_label3', full_name='UPS_login.login_info.user_label3', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=143,
)


_LOGIN_INFO_ASK = _descriptor.Descriptor(
  name='login_info_ask',
  full_name='UPS_login.login_info_ask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_number', full_name='UPS_login.login_info_ask.user_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=182,
)


_LOGIN_INFO_ANS = _descriptor.Descriptor(
  name='login_info_ans',
  full_name='UPS_login.login_info_ans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='UPS_login.login_info_ans.info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='UPS_login.login_info_ans.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=271,
)

_LOGIN_INFO_ANS.fields_by_name['info'].message_type = _LOGIN_INFO
_LOGIN_INFO_ANS.fields_by_name['error'].message_type = common_pb2._ERRORINFO
DESCRIPTOR.message_types_by_name['login_info'] = _LOGIN_INFO
DESCRIPTOR.message_types_by_name['login_info_ask'] = _LOGIN_INFO_ASK
DESCRIPTOR.message_types_by_name['login_info_ans'] = _LOGIN_INFO_ANS

login_info = _reflection.GeneratedProtocolMessageType('login_info', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_INFO,
  __module__ = 'UPS_login_pb2'
  # @@protoc_insertion_point(class_scope:UPS_login.login_info)
  ))
_sym_db.RegisterMessage(login_info)

login_info_ask = _reflection.GeneratedProtocolMessageType('login_info_ask', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_INFO_ASK,
  __module__ = 'UPS_login_pb2'
  # @@protoc_insertion_point(class_scope:UPS_login.login_info_ask)
  ))
_sym_db.RegisterMessage(login_info_ask)

login_info_ans = _reflection.GeneratedProtocolMessageType('login_info_ans', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN_INFO_ANS,
  __module__ = 'UPS_login_pb2'
  # @@protoc_insertion_point(class_scope:UPS_login.login_info_ans)
  ))
_sym_db.RegisterMessage(login_info_ans)


# @@protoc_insertion_point(module_scope)
